export const elements = {
    inputUserName: '#user-name',
    inputPassword: '#password',
    buttonLogin: '#login-button',
    listProduct: '.product_label',
    textFooter: '.footer_copy',
    imageLink4: '#item_4_img_link > .inventory_item_img',
    textError: '[data-test="error"]',
    textLink0: '#item_0_title_link > .inventory_item_name',
    textLink1: '#item_1_title_link > .inventory_item_name',
    textLink2: '#item_2_title_link > .inventory_item_name',
    textLink3: '#item_3_title_link > .inventory_item_name',
    textLink4: '#item_4_title_link > .inventory_item_name',
    textLink5: '#item_5_title_link > .inventory_item_name',
    buttonPrimary: '.btn_primary',
    buttonCartTop: '#shopping_cart_container',
    buttonCartReturn: '.cart_footer > .btn_secondary',
    buttonItemBuy3: ':nth-child(3) > .pricebar > .btn_primary',
    buttonItemBuy4: ':nth-child(4) > .cart_item_label > .item_pricebar > .btn_secondary',
    buttonItemBuy6: ':nth-child(6) > .pricebar > .btn_primary',
    flagCartItem: '.fa-layers-counter',
    buttonRemoveCart: '.item_pricebar > .btn_secondary',
    textItemNameCart: '.inventory_item_name',
    buttonFinish: '.btn_action',
    inputName: '[data-test="firstName"]',
    inputLastName: '[data-test="lastName"]',
    inputPostalCode: '[data-test="postalCode"]',
    textSubTotal: '.summary_subtotal_label',
    textTax: '.summary_tax_label',
    textTotalBuy: '.summary_total_label',
    textFinishBuy: '.complete-header',
};

